
'''工作流终止符'''
class WORKFLOWTERMINAL_dict:    
    def __init__(self, NUMBERTASKSQUEUE=0, TOTALEXECUTETIMEQUEUE=0,NUMBERREMAININGTASKS=0, 
                    TOTALEXECUTETIMEREMAININGTASKS=0,): # SLACKTIME=0,
        self.NUMBERTASKSQUEUE = NUMBERTASKSQUEUE
        self.TOTALEXECUTETIMEQUEUE = TOTALEXECUTETIMEQUEUE
        self.NUMBERREMAININGTASKS = NUMBERREMAININGTASKS
        self.TOTALEXECUTETIMEREMAININGTASKS = TOTALEXECUTETIMEREMAININGTASKS
        # self.SLACKTIME = SLACKTIME

# WORKFLOWTERMINAL_dict = {'NUMBERTASKSQUEUE':0, 'TOTALEXECUTETIMEQUEUE':0,'NUMBERREMAININGTASKS':0, 
#                     'TOTALEXECUTETIMEREMAININGTASKS':0, 'SLACKTIME':0, }
#         # # self.numberTasksQueue = 0  # 在队列中的任务数 the number of tasks in the queue
#         # # self.TOTALEXECUTETIMEQUEUE = 0 # 在队列中任务的执行时间之和  total weight of the operations in the queue. 
#         # # self.numberRemainingTasks = 0  # 剩余任务的数量 the number of remaining tasks
#         # # self.TOTALEXECUTETIMEREMAININGTASKS = 0 #剩余任务的的执行时间之和  total 执行时间 of the remaining tasks. totalWeightRemainingTasks
#         # # self.slackTime = 0 # 松弛时间 deadline减去 当前伪关键路径（剩余任务执行时间之和）的大小
#         # # self.waitingTime = 0 # 等待时间 'WAITINGTIME':0,




'''任务终止符'''
class TASKTERMINAL_dict:    
    def __init__(self, SUBDEADLINE=0, NUMBERSCHILDREN=0,UPWARDRANK=0, 
                    EXECUTETIME=0, AVERAGECOMMUNICATIONTIME=0,
                    NUMBERTASKSQUEUE=0, TOTALEXECUTETIMEQUEUE=0,NUMBERREMAININGTASKS=0, 
                    TOTALEXECUTETIMEREMAININGTASKS=0,NUMBERSFATHER =0, ):
        self.SUBDEADLINE = SUBDEADLINE               #parents=[],SLACKTIME=0, storage=0 ,core=None,deepcopy(TASKTERMINAL_dict)
        self.NUMBERSCHILDREN = NUMBERSCHILDREN
        self.NUMBERSFATHER = NUMBERSFATHER
        self.UPWARDRANK = UPWARDRANK
        self.EXECUTETIME = EXECUTETIME
        self.AVERAGECOMMUNICATIONTIME = AVERAGECOMMUNICATIONTIME
        self.NUMBERTASKSQUEUE = NUMBERTASKSQUEUE               #parents=[], storage=0 ,core=None,deepcopy(TASKTERMINAL_dict)
        self.TOTALEXECUTETIMEQUEUE = TOTALEXECUTETIMEQUEUE
        self.NUMBERREMAININGTASKS = NUMBERREMAININGTASKS
        self.TOTALEXECUTETIMEREMAININGTASKS = TOTALEXECUTETIMEREMAININGTASKS
        # self.SLACKTIME = SLACKTIME

# TASKTERMINAL_dict = {'SUBDEADLINE':0, 'NUMBERSCHILDREN':0, 'UPWARDRANK':0,
#                 'EXECUTETIME':0, 'AVERAGECOMMUNICATIONTIME':0,
#                 'NUMBERTASKSQUEUE':0, 'TOTALEXECUTETIMEQUEUE':0,'NUMBERREMAININGTASKS':0, 
#                     'TOTALEXECUTETIMEREMAININGTASKS':0, 'SLACKTIME':0,} #, 'WAITINGTIME':0
#         # # SUBDEADLINE                 #  子截止时间
#         # # NUMBERSCHILDREN             #  子任务的个数
#         # # UPWARDRANK                  #  HEFT rank值
#         # # EXECUTETIME                 #  执行时间
#         # # AVERAGECOMMUNICATIONTIME    #  平均通讯时间
#         # # # WAITINGTIME                 #  等待时间  # 任务的等待时间 暂时不加入，未找到可解释性
# # 对于任务，其执行时间正比于执行花费，故不在考虑其花费。考虑了与父任务的平均通信时间

'''实例终止符'''
class INSTANCETERMINAL_dict:    
    def __init__(self, ACTUALAVAILABLETIME=0, EXECUTECOST=0,COMMUNICATIONCOST=0, 
                    ACTUALEXECUTETIME=0, INSTANCEAVAILABLETIME=0,NUMBERTASKINCLOUD = 0,SLACKTIME=0,
                    AVERAGEEXECUTECOST=0,AVERAGEEXECUTETIME=0, AVERAGEACTUALAVAILABLETIME = 0,
                    AVERAGEINSTANCEAVAILABLETIME=0,AVERAGESLACKTIME=0):
        self.ACTUALAVAILABLETIME = ACTUALAVAILABLETIME
        self.EXECUTECOST = EXECUTECOST
        self.COMMUNICATIONCOST = COMMUNICATIONCOST
        self.ACTUALEXECUTETIME = ACTUALEXECUTETIME
        self.INSTANCEAVAILABLETIME = INSTANCEAVAILABLETIME
        self.NUMBERTASKINCLOUD = NUMBERTASKINCLOUD
        self.SLACKTIME = SLACKTIME
        '''added 2023 08 16 '''
        self.AVERAGEEXECUTECOST = AVERAGEEXECUTECOST
        self.AVERAGEEXECUTETIME = AVERAGEEXECUTETIME
        self.AVERAGEACTUALAVAILABLETIME = AVERAGEACTUALAVAILABLETIME
        self.AVERAGEINSTANCEAVAILABLETIME = AVERAGEINSTANCEAVAILABLETIME
        self.AVERAGESLACKTIME = AVERAGESLACKTIME        


# class CLOUDPLATFORMTERMINAL_dict:    
#     def __init__(self, COMMUNICATIONCOST=0, AVERAGEEXECUTECOST=0,AVERAGEEXECUTETIME=0, 
#                     INSTANCEAVAILABLETIME=0,NUMBERTASKINCLOUD = 0):
#         self.COMMUNICATIONCOST = COMMUNICATIONCOST
#         self.AVERAGEEXECUTECOST = AVERAGEEXECUTECOST
#         self.AVERAGEEXECUTETIME = AVERAGEEXECUTETIME
#         self.INSTANCEAVAILABLETIME = INSTANCEAVAILABLETIME
#         self.NUMBERTASKINCLOUD = NUMBERTASKINCLOUD

# INSTANCETERMINAL_dict = {'ACTUALAVAILABLETIME':0, 'EXECUTECOST':0, 'COMMUNICATIONCOST':0, 
#                 'ACTUALEXECUTETIME':0, 'INSTANCEAVAILABLETIME':0,}
#         # # ActualAvailableTime     # 在实例上的实际可用时间        
#         # # EXECUTECost              # 执行花费
#         # # COMMUNICATIONcost       # 通信花费
#         # # ActualEXECUTETime        # 在实例上的执行时间
#         # # InstanceAvailableTime   # 实例的可用时间
#         # # NUMBERTASKINCLOUD       # The number of tasks belonging to the same workflow in a cloud

# WORKFLOWTERMINAL_SET = ['NUMBERTASKSQUEUE', 'TOTALEXECUTETIMEQUEUE','NUMBERREMAININGTASKS',
#                         'TOTALEXECUTETIMEREMAININGTASKS', 'SLACKTIME']  # , 'WAITINGTIME'
# TASKTERMINAL_SET = WORKFLOWTERMINAL_SET + ['SUBDEADLINE', 'NUMBERSCHILDREN', 'UPWARDRANK',
#                     'EXECUTETIME', 'AVERAGECOMMUNICATIONTIME']    #, 'WAITINGTIME'
INSTANCETERMINAL_SET = ['ACTUALAVAILABLETIME', 'EXECUTECOST', 'COMMUNICATIONCOST',
                        'ACTUALEXECUTETIME', 'INSTANCEAVAILABLETIME','NUMBERTASKINCLOUD', 'SLACKTIME',
                         'AVERAGEEXECUTECOST', 'AVERAGEACTUALAVAILABLETIME',
                        'AVERAGEEXECUTETIME', 'AVERAGEINSTANCEAVAILABLETIME','AVERAGESLACKTIME']

WORKFLOWTERMINAL_SET = ['NUMBERTASKSQUEUE', 'TOTALEXECUTETIMEQUEUE','NUMBERREMAININGTASKS',
                        'TOTALEXECUTETIMEREMAININGTASKS']  # , 'SLACKTIME', 'WAITINGTIME'
TASKTERMINAL_SET = WORKFLOWTERMINAL_SET + ['SUBDEADLINE', 'NUMBERSCHILDREN','NUMBERSFATHER', 'UPWARDRANK',
                    'EXECUTETIME', 'AVERAGECOMMUNICATIONTIME']    #, 'WAITINGTIME'
# INSTANCETERMINAL_SET = ['ACTUALAVAILABLETIME', 'EXECUTECOST', 'COMMUNICATIONCOST',
#                         'ACTUALEXECUTETIME', 'INSTANCEAVAILABLETIME']  # ,'NUMBERTASKINCLOUD'

# CLOUDPLATFORMTERMINAL_SET = ['COMMUNICATIONCOST', 'AVERAGEEXECUTECOST',
#                         'AVERAGEEXECUTETIME', 'INSTANCEAVAILABLETIME','NUMBERTASKINCLOUD']


FUNCTION_SET = ['ADD','SUB','MUL','PRODIV','MIN','MAX']

# FUNCTION_TERMINAL_WORKFLOW = WORKFLOWTERMINAL_SET + FUNCTION_SET
# FUNCTION_TERMINAL_TASK = TASKTERMINAL_SET + FUNCTION_SET
# FUNCTION_TERMINAL_INSTANCE = INSTANCETERMINAL_SET + FUNCTION_SET
# ALLTERMINAL = TASKTERMINAL_SET + INSTANCETERMINAL_SET  # WORKFLOWTERMINAL_SET + 
# # ALLTERMINAL_DICT = dict(WORKFLOWTERMINAL.items() + TASKTERMINAL.items() + INSTANCETERMINAL.items()) 
# # ALLTERMINAL_dict = {'NUMBERTASKSQUEUE':0, 'TOTALEXECUTETIMEQUEUE':0,'NUMBERREMAININGTASKS':0, 
# #                     'TOTALEXECUTETIMEREMAININGTASKS':0, 'SLACKTIME':0, 
# #                     'SUBDEADLINE':0, 'NUMBERSCHILDREN':0, 'UPWARDRANK':0,
# #                     'EXECUTETIME':0, 'AVERAGECOMMUNICATIONTIME':0,
# #                     'ACTUALAVAILABLETIME':[], 'EXECUTECOST':[], 'COMMUNICATIONCOST':[], 
# #                     'ACTUALEXECUTETIME':[], 'INSTANCEAVAILABLETIME':[],}


# K =1 
# class OPERATE_ADD:
#     def __init__(self, name = None, numbers= 2,parameter1= None,parameter2= None,):
#         name = name
#         numbers = numbers
#         parameter1 = parameter1
#         parameter2 = parameter2
#     # @property
#     # def result(self):
#     #     return self.parameter1 + self.parameter2

# # FUNCTIONSET1 = {'ADD':OPERATE_ADD(name ='ADD',parameter1= 1,parameter2= 2), 'EXECUTECOST':0, 'COMMUNICATIONCOST':0, 
# #                 'ACTUALEXECUTETIME':0, 'INSTANCEAVAILABLETIME':0,}

# # FUNCTIONSET1['ADD']
# # K =1 

# class FUNCTIONSET:
#     def __init__(self,):
#         ADD = None
#         SUB = None
#         MUL = None
#         PRODIV = None
#         MIN = None
#         MAX = None





# 'CURRENTTIME':0CURRENTTIME # 为系统当前时间 或者 已调度任务的最大完成时间

# 'TASKQUEUE'
# 'NUMBERTASKSQUEUE'
# 'TOTALEXECUTETIMEQUEUE'
# 'NUMBERREMAININGTASKS'
# 'TOTALEXECUTETIMEREMAININGTASKS'
# 'SLACKTIME'
# 'WAITINGTIME'
    # taskQueue
    # numberTasksQueue
    # TOTALEXECUTETIMEQUEUE
    # numberRemainingTasks
    # TOTALEXECUTETIMEREMAININGTASKS
    # slackTime
    # waitingTime

# WORKFLOWTERMINAL = {'TASKQUEUE':[], 'NUMBERTASKSQUEUE':None, 'TOTALEXECUTETIMEQUEUE':None, 
#                     'NUMBERREMAININGTASKS':None, 'TOTALEXECUTETIMEREMAININGTASKS':None, 
#                     'SLACKTIME':None, 'WAITINGTIME':None,'CURRENTTIME':None}



# workflowTerminal = {'TASKQUEUE':[], 'NUMBERTASKSQUEUE':None, 'TOTALEXECUTETIMEQUEUE':None, 
#                     'NUMBERREMAININGTASKS':None, 'TOTALEXECUTETIMEREMAININGTASKS':None, 
#                     'SLACKTIME':None, 'WAITINGTIME':None,}
